name: Lua Auto Update

on:
  push:
    paths:
      - '**.lua'   # trigger เมื่อไฟล์ lua เปลี่ยน

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show updated Lua files
        run: |
          echo "Updated Lua files:"
          find . -name "*.lua"

      - name: Run Lua script
        run: lua yourfile.lua
