name: Lua Auto Update

on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  run:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Show updated Lua files
        run: |
          echo "Updated Lua files:"
          find . -name "*.lua"

      - name: Run Lua script
        run: lua yourfile.lua
